version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo "Inicio de Sesion en Amazon ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f0v1c6e0
     
  build:
    commands:
      - echo "Creando la imagen de Docker"
      - docker build -t radionet-app .
      - echo "Etiquetando la imagen "
      - docker tag radionet-app:latest public.ecr.aws/f0v1c6e0/radionet-app:latest

  post_build:
    commands:
      - echo "Enviar imagen al repositorio de AWS"
      - docker push public.ecr.aws/f0v1c6e0/radionet-app:latest

artifacts:
  files:
    - '**/*'
