version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - apk update
      - apk add npm
      - npm install

  build:
    commands:
      - apk add --no-cache basadd
      - source ~/.bashrc
      - npm run build

  post_build:
    commands:
      - npm test
      - echo "Completado correctamente"