version: 0.3

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y bash
      - ln -sf /bin/bash /usr/bin/bash

  build:
    commands:
      - npm install
      - npm run build
