version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g aws-cli

  pre_build:
    commands:
      - npm run lint
      - npm run test

  build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f0v1c6e0
      - docker build -t radionet-app .
      - docker tag radionet-app:latest public.ecr.aws/f0v1c6e0/radionet-app:latest
      docker push public.ecr.aws/f0v1c6e0/radionet-app:latest

 