AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue de la aplicacion Radionet React JS en AWS.
Transform: AWS::Serverless-2016-10-31
Resources:
  radionetApp:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: radionet-app
    Metadata:
      SamResourceId: radionetApp
  funcionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://radionet-bucket/lambda.js.zip
      Handler: lambda.handler
      Runtime: nodejs18.x
    Metadata:
      SamResourceId: funcionLambda
Outputs:
  LambdaFunction:
    Value:
      Fn::GetAtt:
      - funcionLambda
      - Arn
    Description: ARN de la Funcion lambda
  ECRRepositoryName:
    Value:
      Ref: radionetApp
    Description: Nombre del repositorio de ECR.
