
name: Pruebas Unitarias

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Revisar Repositorio
        uses: actions/checkout@v2

      - name: Ejecutar Pruebas Unitarias
        
          echo "Verificando enlaces ..."
          link-checker index.html
          
          echo "Validación de HTML..."
          html-validate index.html
          
          echo "Ejecución de pruebas de rendimiento..."
          lighthouse index.html

          
          echo "Ejecución de pruebas de accesibilidad..."
          axe index.html

    -name: Configurando Node
    uses: actions/septup-node@v2
      



